<?php

namespace AppBundle\Repository;

/**
 * DisabledDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisabledDateRepository extends \Doctrine\ORM\EntityRepository
{
}
