<?php

namespace AppBundle\Repository;

/**
 * FreeDaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreeDaysRepository extends \Doctrine\ORM\EntityRepository
{
}
