security:
    encoders:
        AppBundle\Entity\User: bcrypt
        AppBundle\Entity\Patient: bcrypt
        AppBundle\Entity\Admin: bcrypt
        AppBundle\Entity\Medecin: bcrypt
    providers:
        chain_provider:
            chain:
                providers: [database_users, database_patients, database_admins, database_medecins]
        database_users:
            entity: { class: AppBundle:User, property: email }
        database_admins:
            entity: { class: AppBundle:Admin, property: email }
        database_patients:
            entity: { class: AppBundle:Patient, property: email }
        database_medecins:
            entity: { class: AppBundle:Medecin, property: email }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
